    - name: install mariadb package (CentOS)
      tags: centos,db,mariadb
      dnf:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package (Ubuntu)
      tags: db,mariadb,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: start MariaDB service on CentOS
      service:
        name: mariadb
        state: rest arted
        enabled: true
      when: ansible_distribution == "CentOS"

    - name: start MariaDB service on Ubuntu
      service:
        name: mysql
        state: restarted
        enabled: true
      when: ansible_distribution == "Ubuntu"